Merge pull request from task2 to master
Lendysgo/BotsTg pull request #10
Opened 2023-10-24 18:58 UTC by arsbars24

Сделали задачу 2

2023-10-28 15:27 UTC, vpyzhyanov commented
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/3d44f5bb-d3af-41ab-827d-08ff1231453d)

Даже смотреть не буду. Чек-листы я писал, чтобы в такие ситуации не попадать

2023-10-29 16:50 UTC, arsbars24 commented
Исправили ошибки, проверили по чек-листу.

2023-10-31 05:39 UTC, vpyzhyanov commented
Ошибки в тестах

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/51ce1df5-dcb6-4161-a6a9-020857311498)

Тесты при сборке не запускаются

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/5de7588f-9e62-4aa1-adfc-9ff316f4ee06)

2023-10-31 05:45 UTC, vpyzhyanov commented
Угроза нарушения инкапсуляции. Поле должно быть private
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/c5389104-3eb5-481b-bd7c-ce0e386c5528)

2023-10-31 06:38 UTC, vpyzhyanov requested changes
Всё печально. Тесты не работают, тесты ничего не тестируют. А ещё задача сделана не по постановке, что является фатальной ошибкой.

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/526753c2-78db-4531-a844-3eed064dfbcc)

Нарушена инкапсуляция. Меняйте имя бота и токен кто хочет, можно всё!)))

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +            case "/table":
Задача сделана не по постановке, имя команды другое и текст не на русском языке. Следовательно такая реализация приниматься не будет

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/00d5855b-f4f9-463e-a720-9ceeb1e07f77)

Если вам необходимо сделать задачу по другому, то её необходимо пересогласовать.. Либо делайте по постановке.

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +            default:
Такая команда вообще отсутствует:

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/a14d8c3f-e857-40a5-a96d-53df683b6096)

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Note.java
> +    String text;
где инкапсуляция?

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Note.java
> +    private int id;
Почему поля не final?

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +    private List<Note> notes;
может быть final. IDEA же подсказывает вам?!

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +            if (note.getId() == id) {
похоже тему коллекций вы прогуляли. Недопустимо долго выполняется этот метод. Какова его сложность?

2023-10-31 06:38 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +        notes.removeIf(note -> note.getId() == id);
аналогично

2023-10-31 06:38 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
>  public class LogicTest {
Нет JavaDoc

2023-10-31 06:38 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Note added!", response);
тест некорректен. Сообщение об успешном добавлении не означает фактическое добавление заметки.

2023-10-31 06:38 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(response.contains("Your notes:"));
тест ничего не проверяет. Может он вообще не умеет никакие заметки выводить. А текст никому не интересен, он не является "функционалом"

2023-10-31 06:38 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Note edited!", response);
тест некорректен, он не проверяет, что команда изменилась

2023-10-31 06:38 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Note deleted!", response);
тест некорректен, он не проверяет, что команда удалилась

2023-10-31 08:32 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +            case "/table":
Задача сделана по постановке, вы нам согласовали вот это тз:

![изображение_2023-10-31_133237619](https://github.com/Lendysgo/BotsTg/assets/114307225/b1e15edf-889e-494d-9aad-ca0819886912)
Постановка задачи 2
Цель задачи: Разработать простой блокнот для записей, с возможностью добавлять, изменять и удалять записи.

Планы на развитие:
Расширение блокнота с поддержкой категорий и тегов для записей.
Добавление возможности делиться записями с другими пользователями.
Внедрение функции напоминаний и уведомлений для записей.

Примеры диалога:

П: /help
Б: Привет я простой бот для записей, можешь записывать в меня всё что угодно,
а еще удалять и редактировать записи. Ежедневник в твоем распоряжении.
П: /table
Б: Вот ваши записи 
1….
2….
3….
(каждая запись с отступом \n)
П: /add 1
Б: Добавьте свою первую запись
П:(Пользователь вносит запись)
Б: Запись внесена! ^_^

П: /del 1
Б: Первая запись удалена

П: /edit 1
Б: Вот текст записи: Пример текста записи
Б: Можете вводить изменения в нём
П: (внесение изменений)

2023-11-01 08:39 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +            if (note.getId() == id) {
А да точно тут же 0(n)

2023-11-01 08:40 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +            if (note.getId() == id) {
Исправлено

2023-11-01 08:41 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
Исправлено

2023-11-01 08:41 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/Note.java
> +    private int id;
исправлено

2023-11-01 08:42 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +    private List<Note> notes;
исправлено

2023-11-01 08:42 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +        notes.removeIf(note -> note.getId() == id);
Исправлено

2023-11-02 10:19 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/Note.java
> +    String text;
исправлено

2023-11-02 10:20 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
>  public class LogicTest {
исправлено

2023-11-02 10:20 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Note added!", response);
исправлено

2023-11-08 18:11 UTC, vpyzhyanov commented
Снимаю один балл по Git за незаигнорированные файлы
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/a8aad91d-70dc-4e95-b26c-93d07e919156)

2023-11-08 18:14 UTC, vpyzhyanov commented
static запрещён 
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/a4a7afee-1cdf-4431-a4fc-a16726845a11)

2023-11-08 18:17 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +            case "/table":
ок, разобрались

2023-11-08 18:22 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/NoteManager.java
> +            if (note.getId() == id) {
верно

2023-11-08 18:33 UTC, vpyzhyanov commented
> Снимаю один балл по Git за незаигнорированные файлы ![image](https://user-images.githubusercontent.com/71599019/281501845-a8aad91d-70dc-4e95-b26c-93d07e919156.png)

Этого можно было легко избежать, прочитав чек-листы (да, там это есть). Но вы написали:

> Исправили ошибки, проверили по чек-листу.

Поэтому балл снят без возможности восстановления. Так что исправьте, пока мы не дошли до следующих задач.

2023-11-08 18:34 UTC, vpyzhyanov requested changes
Исправьте последние замечания и можете мёрджить

2023-11-08 18:34 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains("1. Test Note"));
лучше проверять на equals, тогда в случае ошибки можно будет увидеть какое сообщение было получено, а какое ожидалось

2023-11-08 18:34 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(response.contains("1. Test Note"));
здесь тоже можно было всё одной проверкой `assertEquals` сделать.

2023-11-08 18:34 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains(" "));
Тест ничего не проверяет. Вот тут `contains `сыграл с вами злую шутку. Обратите внимание, что если вернётся **любое** сообщение, содержащее пробел, то тест пройдёт. А это почти **любое** сообщение. Какая бы неправильная не была логика, тест всё равно будет проходить.

2023-11-08 18:34 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains(" "));
то же самое. Тест ничего не проверяет.

2023-11-08 18:34 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Следуй по командам", response);
Какой-то странный ответ. По каким командам надо следовать? Можно тут стоило написать, что это неизвестная команда и нужно использовать команду /help, чтобы увидеть все команды?

2023-11-12 08:53 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(response.contains("1. Test Note"));
Исправлено

2023-11-12 08:54 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains(" "));
Ну да, в любой команде будет пустая подстрака. Исправлено

2023-11-12 08:54 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains(" "));
Исправлено

2023-11-12 08:54 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Следуй по командам", response);
Исправлено

2023-11-12 08:54 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertTrue(logic.handleMessage("/table").contains("1. Test Note"));
Исправлено

2023-11-13 16:23 UTC, merged

2023-11-18 17:21 UTC, vpyzhyanov commented
Ребята, это что за ерунда?
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/854acb96-a2cc-49d7-ac81-7ca9fe9a0262)

Особенно это:
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/695c00e6-053c-431f-87e9-527a24818a7d)

Заигнорированы **исходные коды**!

Вы такими темпами будете получать 0 баллов за Git.

И даже замечание по прежнему не исправлено
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/a9ec3edf-9055-4f9d-b5f8-31d3ccd3b423)

Я же вам рассказывал как использовать gitignore, даже в чек листе прописал что именно нужно заигнорировать. Что пошло не так?

Ещё раз: игнорировать нужно папки, а не отдельные файлы. Вот вам не лень по одному файлу игнорировать. Обязательно что-нибудь забудете. Папки ".target" не существует, существует только "target". Папки ".config" тоже не существует.
А исходные коды игнорировать неразумно. Надеюсь не надо объяснять почему.