Task 3
Lendysgo/BotsTg pull request #18
Opened 2023-11-07 19:21 UTC by arsbars24

Implement functionality for creating, deleting, and renaming categories. Add the ability to add notes to categories.

2023-11-18 17:33 UTC, vpyzhyanov commented
Объясните вот это, пожалуйста
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/40076217-54c1-49b9-8115-07afd6e2023b)

Как у вас была разделена работа?

2023-11-18 18:11 UTC, vpyzhyanov requested changes
Есть замечания.

А ещё случилось страшное: вы **затёрли функционал предыдущий задачи**. А именно потеряна возможность редактировать и удалять заметки. Функционал должен расширяться, а не сужаться.

2023-11-18 18:11 UTC, vpyzhyanov commented on .gitignore
> +/target/classes/ru/mathmeh/urfu/bot/TelegramBot.class
что это такое? Не так я учил настраивать игнорирование файлов

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +    Categories categories;
Нет инкапсуляции. Область видимости позволяет делать **всё что угодно** в пределах пакета

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +            parsedCommand[0] = words[0].substring(1);  // Убираем "/"
А вы ведь даже не проверили есть ли вообще в этой строке "/". Лучше сделать `words[0].replace("/", "")`

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +import ru.mathmeh.urfu.bot.Notes.Note;
Неиспользуемый импорт

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +                    ("Категория " + categoryName + " уже существует.");
открывающую скобку принято писать сразу после имени метода или конструктора.
```
            throw new IllegalArgumentException (
                    "Категория " + categoryName + " уже существует.");
```

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +public class Categories {
молодцы, что выделили отдельный класс

2023-11-18 18:11 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +            result.append(index).append(". ").append(category).append("\n");
Добро пожаловать на тёмную сторону ООП. Ваш класс берёт на себя слишком много, он занимается не только управлением категориями, но и форматированием вывода. Выделите это в отдельный класс.

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual: " + response);
всю отладочную информацию надо убрать

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual: " +listCategoriesResponse );
всю отладочную информацию надо убрать

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual:\n" + response);
всю отладочную информацию надо убрать

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testeditCategoryCommand() {
Слово `edit` должно быть с большой буквы

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testdeleteCategoryCommand() {
Слово `delete` должно быть с большой буквы

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testaddtoCategoryCommand() {
Слово `add` должно быть с большой буквы

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals(expected.trim(), listCategoriesResponse.trim());
Странно вызывать `trim()` у expected, т.к. вы сами его пишете и у вас там нет пробельных символов ни в начале, ни в конце.

На самом деле у listCategoriesResponse вызывать `trim()` тоже не стоит, т.к. стоит проверить полный формат возвращаемого значения. Вдруг там несколько переводов строк в конце и это будет мешать пользователю, а тесты такое пропустят.

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        String expected = "Записи в категории \"тест\":\n" + "- тест1\n";
Если в строке есть перевод строки, то лучше писать их тоже в несколько строк, так нагляднее

```
String expected = """
                Записи в категории "тест":
                - тест1
                """;
```

Даже IDEA вам предлагает преобразовать эту строку.

2023-11-18 18:11 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +
Нет теста на `/list_categories`

Нет теста на `/list_notes`

2023-11-19 17:04 UTC, arsbars24 commented on .gitignore
> +/target/classes/ru/mathmeh/urfu/bot/TelegramBot.class
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testaddtoCategoryCommand() {
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testdeleteCategoryCommand() {
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testeditCategoryCommand() {
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual:\n" + response);
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual: " +listCategoriesResponse );
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        System.out.println("Actual: " + response);
Исправлено

2023-11-19 17:23 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +                    ("Категория " + categoryName + " уже существует.");
Исправлено

2023-11-19 17:24 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +import ru.mathmeh.urfu.bot.Notes.Note;
Исправлено

2023-11-19 17:24 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +            parsedCommand[0] = words[0].substring(1);  // Убираем "/"
Исправлено

2023-11-19 17:24 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +    Categories categories;
Исправлено

2023-11-20 16:23 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +            result.append(index).append(". ").append(category).append("\n");
Сделал класс Printer, который используется там, где нужен вывод. 
Исправлено

2023-11-20 16:37 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals(expected.trim(), listCategoriesResponse.trim());
Исправлено

2023-11-20 16:37 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        String expected = "Записи в категории \"тест\":\n" + "- тест1\n";
Исправлено

2023-11-28 15:41 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +
Исправлено

2023-12-04 19:07 UTC, vpyzhyanov commented
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/d027af1c-df6f-4320-bdec-060b9aa3cce2)

Вообще-то это я писал именно для вас:

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/591b2196-808e-420c-82f6-42aea1c5553c)

И полный игнор.... вы чат не читаете?

2023-12-04 19:16 UTC, vpyzhyanov commented
> Объясните вот это, пожалуйста ![image](https://private-user-images.githubusercontent.com/71599019/284014119-40076217-54c1-49b9-8115-07afd6e2023b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTY3NzYsIm5iZiI6MTcwMTcxNjQ3NiwicGF0aCI6Ii83MTU5OTAxOS8yODQwMTQxMTktNDAwNzYyMTctNTRjMS00OWI5LTgxMTUtMDdhZmQ2ZTIwMjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE5MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YmJhMjVhMGNkZTFhYjJmNmJlZDI2MjllMjQ2MGQ3NmNhODc5MDMxNjVhN2VkMWIwNDFmZmMzNjZjOTM2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r6ZA-woOTbt57rYsKzD0jinxgRnuBCfxQnjmM88_bO4)
> 
> Как у вас была разделена работа?

С ответом на этот вопрос вам нужно подойти ко мне завтра

2023-12-04 19:54 UTC, vpyzhyanov requested changes
Задача опять сделана не по постановке!

> 1) Тесты совершенны, хотели бы получить доп. балл

Тестов не хватает. Написал в замечании чего не хватает.

> 2) Добавлена платформа Вк(доп. балл)

Нужно продемонстрировать на паре

> 3) Добавлены кнопки(Bot special)

Нужно продемонстрировать на паре

> проект задеплоин(доп. бал)

Не вижу результата. Нужно показать, что бот действительно задеплоен и нужно написать инструкцию по деплою.

За гит снял один балл за то, что не используете ветки и пулл реквесты.

2023-12-04 19:54 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +        assertEquals("Неревный номер записи.", response);
опечатка

2023-12-04 19:54 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/Main.java
> +        new VkBot().startPolling();
оба бота должны использовать одну и ту же логику (пользоваться одними и теми же данными)

2023-12-04 19:54 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Categories.java
> +        List<String> categoryList = new ArrayList<>(categories.keySet());
Без создания списка можно легко обойтись

2023-12-04 19:54 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/VkBot.java
> +        this.logic = new Logic();
получается данные у каждой платформы свои. А надо чтобы были одни и те же

2023-12-04 19:54 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testAddToCategoryCommand() {
Не хватает тестов:
1. Нет теста, на добавление заметки в категорию, которой не существует.
2. Нет тест на изменение несуществующей категории
3. Все предыдущие, но для обычных заметок.
4. Что будет если ввести "/added тест1 to"
5. Что если ввести произвольный текст вместо команды

Ну и тесты не могут быть идеальными, если они даже при сборке не запускаются

2023-12-04 19:54 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic/Logic.java
> +                        /added <> to <> - добавление записи в категории 📩
В постановке, которая записана у меня такой команды не существует. Даже в вашей постановке нет такой команды:
![image](https://github.com/Lendysgo/BotsTg/assets/71599019/e3500bc1-08f3-4c35-8a6f-75145e66b4fc)

Итого: **задача сделана не по постановке**

2023-12-06 15:21 UTC, vpyzhyanov commented
Никогда так не делайте в открытом пулл реквесте! Этим действием вы заставляете код ревьюера посмотреть всё ревью заново!

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/095ab51e-51dc-4918-8678-90f11e4b639a)

2023-12-06 15:21 UTC, vpyzhyanov requested changes

2023-12-06 15:21 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +    public void testAddToUnexistCategoryCommand() {
У нового теста старое описание из другого теста

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/527ea7ef-1d0b-42fe-b77c-6e0854b69720)

2023-12-22 07:52 UTC, merged