Task1
Lendysgo/BotsTg pull request #2
Opened 2023-10-10 09:46 UTC by Lendysgo

Выполненная первая задача. Бот отвечает на команды /start, /help. Остальные сообщения от пользователя отзеркаливаются

2023-10-12 18:07 UTC, vpyzhyanov commented
Вы поймали большинство этих ошибок:
1️⃣ Не прошлись по чек-листу "Чек-лист по подготовке задачи к сдаче"
2️⃣ Не прошлись по чек-листу "Чек-лист для получения максимума баллов за Git"
3️⃣ Отсутствует тест на главную функциональность (например, есть тесты на команду /start и /help, но нет теста на возврат ботом текста от пользователя)
P.S. Тестировать /start и /help не нужно, в этом нет смысла
4️⃣ Не запускается тест на компьютере преподавателя, т.к. не прописан токен бота. Причина: ваш тест не функциональный, он интеграционный, значит вы не выделили логику бота в отдельный класс (например Logic). Все тесты должны запускаться без ввода дополнительных параметров.
Решение: Выделить всю логику обработки сообщений в отдельный класс и тестировать только его.
5️⃣ Нарушена логика зависимостей классов, а именно логика обработки сообщений зависит от бота. В частности логика зависит от реализации Телеграмм бота. 
Как понять, что у вас такая зависимость? В классе, отвечающего за логику (обработку сообщений) в импортах присутствует "org.telegram.telegrambots"
В будущем это вызовет огромные проблемы при попытке добавить ещё одну чат платформу.
Решение: Не логика зависит от бота, а бот зависит от логики. То есть в классе Logic нужно использовать интерфейс "Bot", который вы написали сами, а реализация этого интерфейса будет отличаться для разных платформ. При добавлении новой чат платформы логику менять не придётся.
6️⃣ Отсутствуют JavaDoc
Решение: написать JavaDoc на все классы и методы. Особенно на тесты.
7️⃣ Над задаче работал только один человек из команды. Такая работа оценивается в 0 баллов.
8️⃣ Не использовали ветки. Всю работу делали в main.
Решение: использовать ветки c номером задачи (task1) и с именами участников (task1-petrov).
9️⃣ Отсутствуют комментарии в PullRequest, это значит, что вы не использовали PullRequest.
Решение: Второй участник команды смотрит код (code review) в этом пулл реквесте. Если у него есть замечания/предложения, то нужно их написать. Если замечаний нет, то нужно добавить комментарий, что всё хорошо.
1️⃣0️⃣ Не заигнорированы файлы настроек проекта и скомпилированные классы. После сборки проекта на вкладке Commit появляются "Unversioned Files"
Решение: добавить в .gitignore: .idea. *.iml, target

2023-10-12 18:08 UTC, vpyzhyanov requested changes
tofix

2023-10-12 18:08 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramMessageHandler.java
> +    public SendMessage parse(Message message){
Нарушена логика зависимостей классов, а именно логика обработки сообщений зависит от бота. В частности логика зависит от реализации Телеграмм бота. 
Как понять, что у вас такая зависимость? В классе, отвечающего за логику (обработку сообщений) в импортах присутствует "org.telegram.telegrambots"
В будущем это вызовет огромные проблемы при попытке добавить ещё одну чат платформу.
Решение: Не логика зависит от бота, а бот зависит от логики. То есть в классе Logic нужно использовать интерфейс "Bot", который вы написали сами, а реализация этого интерфейса будет отличаться для разных платформ. При добавлении новой чат платформы логику менять не придётся.

2023-10-12 18:08 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramMessageHandler.java
> + * @author lendys(Yaroslav Prisepnyj)
Не хорошо копипасить чужой код!

2023-10-12 18:08 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
> +    public static String BOT_TOKEN;
Настоятельно рекомендую вам полностью отказаться от ключевого слова "static". Он мешает вам осваивать ООП.

2023-10-12 18:08 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/TelegramMessageHandlerTest.java
> +class TelegramMessageHandlerTest {
Нет теста на основную функциональность

2023-10-12 18:08 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/TelegramMessageHandlerTest.java
> +        Message msg = new Message();
Вы точно хотите завязываться на телеграмм? Не стоит

2023-10-15 13:47 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/TelegramMessageHandler.java
> +    public SendMessage parse(Message message){
Исправили, логику обработки сообщений вынесли в отдельный класс и реализовали интерфейс бота

2023-10-15 14:17 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/TelegramMessageHandlerTest.java
> +class TelegramMessageHandlerTest {
Добавили тест на основную функциональность .

2023-10-15 15:23 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
> +    public static String BOT_TOKEN;
убрали static

2023-10-16 07:46 UTC, vpyzhyanov requested changes
Есть замечания. Как исправите, можете мёрджить. Задача принята.

2023-10-16 07:46 UTC, vpyzhyanov commented on .gitignore
> +.idea. *.iml
`.idea` указана дважды

2023-10-16 07:46 UTC, vpyzhyanov commented on .gitignore
> +.target
нет такой папки, есть папка `target`

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/Main.java
> +            config.load();
Зачем-то загрузку делает дважды

![image](https://github.com/Lendysgo/BotsTg/assets/71599019/67dcc8ce-cc3c-4dc9-b967-619a62090359)

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
> +    public String BOT_NAME;
Теперь это обычные поля и должны иметь именоваться так: `botName`

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> + * class MessageHandler
Нет описания

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +    public String messageHandler(String message){
`messageHandler` - это имя объекта. У вас метод. Так что имя метода кардинально расходится с тем, что написано в описании. А в описании вообще написана какая-то дополнительная информация, а описания самого метода отсутствует!

Лучше метод назвать `handleMessage` или что-то вроде того, главное чтобы там был **глагол**.

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramBot.java
> +    private final Logic telegramLogic;
при чём тут telegram? Речь была о том, что логика ни зависит от чат платформы

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramBot.java
> +    Config config = new Config();
Почему одно поле инициализируете в конструкторе, а другое сразу в поле класса?

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramBot.java
> +        return config.BOT_NAME;
инкапсуляция - "до свидания". Имя бота может изменить кто угодно и как угодно.

2023-10-16 07:46 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> + *class LogicTest
нет описания. Все и так видят что это класс и что он называется именно так

2023-10-16 07:46 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> + * testing commands \start and \help
1. описание пишется в самом начале
2. Название и описание не соответствуют друг другу, судя по описаю класс должен называться `StartHelpLogicTest`
3. Описание не соответствует содержимому класса, тест тестирует не только это

Совет: в описании класса пишите более общиее назначение теста. Например, тестирование класса `Logic`. А описание тестирования конкретной функциональности (команд) должно быть в описании методов.

2023-10-16 07:46 UTC, vpyzhyanov commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +     * method testDefaultCase
не надо писать очевидные вещи. Вы ещё бы написали что это JavaDoc))))

2023-10-16 07:46 UTC, vpyzhyanov commented on src/main/java/ru/mathmeh/urfu/bot/TelegramMessageHandler.java
> +    public SendMessage parse(Message message){
Молодцы, теперь бот готов расширяться

2023-10-16 13:28 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/Main.java
> +            config.load();
fixed

2023-10-16 13:28 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
> +    public String BOT_NAME;
fixed

2023-10-16 13:28 UTC, daewiguru commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> + * class MessageHandler
fixed

2023-10-16 13:28 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> +    public String messageHandler(String message){
fixed

2023-10-16 13:28 UTC, Lendysgo commented on src/main/java/ru/mathmeh/urfu/bot/TelegramBot.java
> +    private final Logic telegramLogic;
fixed

2023-10-16 13:29 UTC, daewiguru commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> + *class LogicTest
fixed

2023-10-16 13:29 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> + * testing commands \start and \help
fixed

2023-10-16 13:29 UTC, Lendysgo commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> +     * method testDefaultCase
fixed

2023-10-17 04:08 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/Main.java
> +            config.load();
Исправлено

2023-10-17 04:11 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Config.java
> +    public String BOT_NAME;
Исправлено

2023-10-17 04:11 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/Logic.java
> + * class MessageHandler
Исправлено

2023-10-17 04:12 UTC, arsbars24 commented on src/main/java/ru/mathmeh/urfu/bot/TelegramBot.java
> +    Config config = new Config();
Исправлено

2023-10-17 04:15 UTC, arsbars24 commented on src/test/java/ru/mathmeh/urfu/bot/LogicTest.java
> + *class LogicTest
Исправлено

2023-10-17 04:16 UTC, merged